ORNL/CabanaPD

.github/workflows/CI.yml
.github/workflows/Nightly.yml
.github/workflows/format-check.yml
src/CabanaPD_Particles.hpp

Add CI with GitHub Actions

---

.github/workflows/CI.yml
src/CabanaPD_Comm.hpp

Shouldn't be using Cabana `Impl`, but just fix for the interface change right now

Fix unique topology

---

src/CabanaPD_Solver.hpp

Count all force/comm/init timing contributions correctly

Improve timers

---

src/CabanaPD_Input.cpp
src/CabanaPD_Solver.hpp

Only one rank needs to print timing/thermo info

Only open output files on one rank

---

examples/elastic_wave.cpp
examples/kalthoff_winkler.cpp
src/CabanaPD_Comm.hpp
src/CabanaPD_Force.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
unit_test/tstComm.hpp
unit_test/tstForce.hpp
unit_test/tstIntegrator.hpp

Different classes for PMB and LPS

Separate model tags, properties, and communication

---

README.md

Update readme spack install instructions to use master

---

examples/CMakeLists.txt
examples/crack_branching.cpp
examples/kalthoff_winkler.cpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Comm.hpp
src/CabanaPD_Force.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp

Add new crack branching example. Make boundary conditions more flexible to enable this problem (applied top and bottom)

Example: crack branching

---

src/CabanaPD_Force.hpp

Compute LPS critical stretch parameter based on influence function

---

.github/workflows/CI-e4s-build.yml
.github/workflows/CI.yml
.github/workflows/Nightly.yml
src/CabanaPD_Comm.hpp
src/CabanaPD_Particles.hpp

Removed unused halo neighbors from Particles classes

Cabana topology functions moved out of Impl

---

src/CabanaPD_Integrate.hpp
src/CabanaPD_Solver.hpp
unit_test/tstIntegrator.hpp

Please check and confirm the change in CabanaPD_Solver.hpp is correct.

remove unused mvv2e factor

---

LICENSE
examples/crack_branching.cpp
examples/elastic_wave.cpp
examples/kalthoff_winkler.cpp
src/CabanaPD.hpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Comm.hpp
src/CabanaPD_Force.hpp
src/CabanaPD_Input.cpp
src/CabanaPD_Input.hpp
src/CabanaPD_Integrate.hpp
src/CabanaPD_Output.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Prenotch.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
src/CabanaPD_config.hpp.cmakein
unit_test/TestCUDA_Category.hpp
unit_test/TestHIP_Category.hpp
unit_test/TestOPENMP_Category.hpp
unit_test/TestPTHREAD_Category.hpp
unit_test/TestSERIAL_Category.hpp
unit_test/mpi_unit_test_main.cpp
unit_test/tstComm.hpp
unit_test/tstForce.hpp
unit_test/tstIntegrator.hpp

Update license for 2023

---

README.md

Added reference to crack-branching example in README file

---

examples/crack_branching.cpp
examples/elastic_wave.cpp
examples/kalthoff_winkler.cpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Comm.hpp
src/CabanaPD_Force.hpp
src/CabanaPD_Input.cpp
src/CabanaPD_Input.hpp
src/CabanaPD_Integrate.hpp
src/CabanaPD_Output.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Prenotch.hpp
src/CabanaPD_Solver.hpp
unit_test/tstComm.hpp
unit_test/tstForce.hpp
unit_test/tstIntegrator.hpp

No intended changes other than style convention

Rename functions with camelCase

---

examples/crack_branching.cpp
examples/kalthoff_winkler.cpp
src/CabanaPD.hpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Comm.hpp
src/CabanaPD_Fields.hpp
src/CabanaPD_Particles.hpp

Also remove the previous, very specific, crack branch BC from the source code

Add particle lists for force and position for crack branch BC

---

README.md

- Minimum Cabana version
- Remove reference to Cajita
- Update out of date wiki link

readme: update Cabana details

---

src/CabanaPD_Particles.hpp

Custom particle init

---

src/CabanaPD_Solver.hpp

Added constructor without pre-notch + created function outside constructor to initialize mu.

Added option to not define pre-notch

---

examples/crack_branching.cpp
examples/elastic_wave.cpp
examples/kalthoff_winkler.cpp

Added section labels to examples for clarity and made sections order consistent between examples.

Examples section labels

---

.pre-commit-config.yaml
src/CabanaPD_Force.hpp

Using codespell pre-commit check. Only once instance in the code so far :)

Add comment spell check

---

examples/inputs/crack_branching.json
examples/inputs/elastic_wave.json
examples/inputs/kalthoff_winkler.json
src/CabanaPD_Input.hpp

Added critical time step calculation and warning if actual time step is larger
Fixes #8

Critical time step

---

src/CabanaPD_Solver.hpp

Bug introduced in recent bugfix #122

Fix MPI error by removing in place reduce in solver

---

README.md

Add features in readme

---

CMakeLists.txt

Release 0.3

---

src/CabanaPD_Particles.hpp

…with order of arguments in Line 109

Changed order of sliceVelocity and sliceStrainEnergy in Particles class

---

src/CabanaPD_Solver.hpp

to account for thermal_subcycle_steps > 1

Changed heat transfer time step in solver 

---

README.md

Missing heat transfer, output options, contact

readme: describe new capabilities

---

.github/workflows/CI.yml
.github/workflows/Nightly.yml

This is just on start-up - we use our own containers on the next line

CI: run on ubuntu:latest

---

src/CabanaPD_Solver.hpp

Mistake for per-step output. Final value was correct

fixup: incorrect particle steps per second output

---

examples/dem/powder_fill.cpp
examples/mechanics/crack_branching.cpp
examples/mechanics/dogbone_tensile_test.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/kalthoff_winkler.cpp
examples/mechanics/random_cracks.cpp
examples/thermomechanics/thermal_crack.cpp
examples/thermomechanics/thermal_deformation.cpp
examples/thermomechanics/thermal_deformation_heat_transfer.cpp
examples/thermomechanics/thermal_deformation_heat_transfer_prenotched.cpp
src/CabanaPD_BodyTerm.hpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_HeatTransfer.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
src/force_models/CabanaPD_Contact.hpp
src/force_models/CabanaPD_Hertzian.hpp
src/force_models/CabanaPD_LPS.hpp
src/force_models/CabanaPD_PMB.hpp
unit_test/tstComm.hpp
unit_test/tstForce.hpp
unit_test/tstHertz.hpp
unit_test/tstIntegrator.hpp
unit_test/tstParticles.hpp

Also slowly start to remove shared pointers (Solver and Particles classes here)
Closes #168

Use CTAD and remove create functions

---

examples/dem/powder_fill.cpp
examples/mechanics/crack_branching.cpp
examples/mechanics/dogbone_tensile_test.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/kalthoff_winkler.cpp
examples/mechanics/plate_with_hole.cpp
examples/mechanics/random_cracks.cpp
examples/thermomechanics/thermal_crack.cpp
examples/thermomechanics/thermal_deformation.cpp
examples/thermomechanics/thermal_deformation_heat_transfer.cpp
examples/thermomechanics/thermal_deformation_heat_transfer_prenotched.cpp

Issue in combining #190 with #188, where the previous `shared_ptr` hid some of this

Particles must be extracted from Solver once created

---

src/CabanaPD_Input.hpp

Also added use case error if m and horizon are both input.

added ability to input m into input file, and calculate horizon.

---

src/CabanaPD_Particles.hpp

Remove feature only worked with base particle fields

Fix particle removal for non-base particle fields

---

src/CabanaPD_Particles.hpp

Update global count after removal

---

src/CabanaPD_Input.hpp

Introduced in #173 
Closes #244

Fix vector size mistake from multi-material

---

README.md

Some missing examples, moved to list format for readability, some small clarifications

Update readme example descriptions
