ORNL/CabanaPD

examples/elastic_wave.cpp
examples/kalthoff_winkler.cpp
src/CabanaPD_Comm.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp
unit_test/tstComm.hpp
unit_test/tstForce.hpp
unit_test/tstIntegrator.hpp

Includes optimization to only communicate positions and volumes once, then uses the same buffers for all communication of weighted volume, dilatation, and displacement rather than recreating every step

Use Cabana communication buffer optimization

---

src/CabanaPD_Prenotch.hpp

New warnings in the CI from cmath functions. Use Kokkos math (instead of `std`) to work on the device (different namespaces for different versions)

Use Kokkos math functions

---

.github/workflows/CI.yml
.github/workflows/Nightly.yml
CMakeLists.txt
README.md
src/CabanaPD_Particles.hpp

Default to HDF5 output; if not available, use Silo output. If neither are compiled with Cabana, warn that no particle output is available

Add Cabana HDF5 particle output

---

src/CabanaPD_Boundary.hpp

fixup: boundary member variable device capture

---

src/CabanaPD_Force.hpp

Changes made to the force calculation for performance improvement. 
Results below based on the KalthoffWinkler example with: 
- std::array<int, 3> num_cell = { 400, 800, 36 };
- double delta = 0.00150000001;
running on 1 node of Frontier with 8 GPUs.
For the PMB model:
-------------------
Changes to the force calculation reduces:
- force calculation time from 313.90 s to 294.73 s (~6.1% reduction)
- communication time from 5.12 s to 3.82 s (~25.4% reduction)
- total time from 339.62 s to 316.45 s (~6.8% reduction)
For the LPS model:
------------------
(a) Changes to the weighted volume calculation reduces communication time from 383.48 s to 371.92 s (~3% reduction)
(b) Changes to the dilatation calculation in addition to (a) reduces communication time from 383.48 s to 350.14 s (~8.7 % …

Changes to mu_ij if statements for performance improvements

---

CMakeLists.txt

- Broken with Cajita deprecation
- Will still fail at link if not found

Remove error if Cajita not enabled

---

src/CabanaPD_Comm.hpp
unit_test/tstComm.hpp

Performance improvement (checked on GPU) and simplification of particle halo search. Should enable better reuse for contact ghost neighbors

Rearrange halo search

---

examples/crack_branching.cpp

@streeve : "Pa" is the unit of traction. The unit of body force density is "N/m^3" which is equal to "Pa/m"

Fix unit for body force density

---

examples/elastic_wave.cpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Solver.hpp

Will be used for temperature, etc. (but this is only preparation for that capability)

Add boundary conditions to elastic

---

src/CabanaPD.hpp
src/CabanaPD_BodyTerm.hpp

"boundary condition" applied to all local particles. Can be passed to the solver just like a BC

Create body term

---

examples/elastic_wave.cpp
src/CabanaPD.hpp
src/CabanaPD_DisplacementProfile.hpp

To be reused in future examples

Displacement profile output

---

examples/mechanics/crack_branching.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/kalthoff_winkler.cpp

Separate headings in mechanics example to be consistent with thermal_deformation example

Added solver heading and separate it from run heading for consistency

---

src/CabanaPD_Particles.hpp

Previous version only allowed standard (dense) particle creation with LPS/temperature. Expanded to enable custom creation
Closes #115

Custom particle creation for LPS and thermal systems 

---

README.md
examples/mechanics/CMakeLists.txt
examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/inputs/fragmenting_cylinder.json
src/CabanaPD_Particles.hpp

Adds new fragmentation example

Fragmenting cylinder example

---

src/CabanaPD_Solver.hpp

`maxNeighbors` and `totalNeighbors` cannot necessarily be accessed directly on the host, causing runtime failure for GPU. 
Introduced in #76 (max neighbors is a special case that does not require device access for 2d layouts, but that is not the case for total). This also guards against future changes in neighbor layouts (at the cost of a single init kernel launch)
Fixes #121

Fix neighbor interface device access in solver

---

examples/mechanics/crack_branching.cpp
examples/mechanics/kalthoff_winkler.cpp
src/CabanaPD_Boundary.hpp

1) Separates geometry from region for BC; adds cylinder as additional example
2) Simplification for cases of only one plane
3) Unify interface to use time in all BC
4) Adds options for user-defined regions or a boundary index space (for full customization)
Currently partially embedded in #108

Generalize boundary condition options

---

examples/mechanics/kalthoff_winkler.cpp

Modified the boundary region ("plane") for clarity. It is assumed we use a cell-centered grid of particles, so that the leftmost particles are located in the x-direction at x_bc + 0.5*dx. We can consider extending the plane definition, if needed.

Changed b.c. region in KW example for consistency with the particle grid

---

examples/mechanics/crack_branching.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/kalthoff_winkler.cpp
examples/thermomechanics/thermal_crack.cpp
examples/thermomechanics/thermal_deformation.cpp
src/CabanaPD_Particles.hpp

Includes option for passing input class directly (example in crack branching)
Unrelated change: unneeded empty prenotch in fragmentation problem

Add particle class creation functions

---

examples/thermomechanics/thermal_deformation_heat_transfer.cpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Types.hpp

Follow on to #108 for `createParticles` with heat transfer

Enable createParticles for thermal examples

---

src/CabanaPD_Force.hpp
src/CabanaPD_HeatTransfer.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp
src/force/CabanaPD_Force_LPS.hpp
src/force/CabanaPD_Force_PMB.hpp
unit_test/tstForce.hpp

Template on memory since it now stores class data. Use default execution space for now. Will greatly simplify dual horizon approach #146 and contact/DEM lists #143 (to be rebased on this PR)

Move neighbor list into force

---

src/CabanaPD_Force.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Types.hpp
unit_test/tstForce.hpp

- Separates output fields from those for primary updates
- Makes energy output fully optional (on by default)
- Also includes damage calculation (fused kernel with energy)
- Greatly simplifies calls to Cabana output with variadic fields 
- Preparing for optional stress in #137, blocked by this PR

Make energy optional

---

src/CabanaPD_Input.hpp

Also adds errors if neither are available

Add dimension and consistency checks for  size / corners and num_cells / dx

---

.github/workflows/CI.yml
CMakeLists.txt
src/CabanaPD.hpp
src/CabanaPD_Particles.hpp
src/force/CabanaPD_Force_HertzianContact.hpp
src/force/CabanaPD_HertzianContact.hpp
unit_test/CMakeLists.txt
unit_test/inputs/hertzian_contact.json
unit_test/tstHertz.hpp

This PR adds the Hertzian force model for DEM simulations.

DEM Force Model

---

examples/mechanics/fragmenting_cylinder.cpp
src/CabanaPD_BodyTerm.hpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Comm.hpp
src/CabanaPD_DisplacementProfile.hpp
src/CabanaPD_Force.hpp
src/CabanaPD_HeatTransfer.hpp
src/CabanaPD_Integrate.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Prenotch.hpp
src/CabanaPD_Solver.hpp
src/force/CabanaPD_Force_Contact.hpp
src/force/CabanaPD_Force_HertzianContact.hpp
src/force/CabanaPD_Force_LPS.hpp
src/force/CabanaPD_Force_PMB.hpp
unit_test/CMakeLists.txt
unit_test/tstComm.hpp
unit_test/tstForce.hpp
unit_test/tstParticles.hpp

Also adds particle class methods for owned, ghost, and global sizes (separate commit)

Enable frozen points for boundaries

---

examples/mechanics/inputs/fragmenting_cylinder.json

Enforced since #155, but missing in this example

fixup: missing unit input

---

examples/mechanics/fragmenting_cylinder.cpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Types.hpp

Simplify the fragmenting cylinder example in the process. Note that this only works with the uniform values across all particles currently assumed (volume is the most obvious example) since only the positions are selectively assigned. This just means that even particles not created should be initialized. For further custom creation a split loop will be necessary.

Enable custom init in particle construction

---

src/CabanaPD_Constants.hpp
src/CabanaPD_Force.hpp
src/CabanaPD_Prenotch.hpp
src/force/CabanaPD_ForceModels_LPS.hpp
src/force/CabanaPD_ForceModels_PMB.hpp
src/force/CabanaPD_Force_HertzianContact.hpp
src/force/CabanaPD_HertzianContact.hpp

Updated min to Kokkos 4.1 in #158 
Prefer direct usage rather than `using`

Use Kokkos math

---

examples/mechanics/crack_branching.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/kalthoff_winkler.cpp
examples/thermomechanics/thermal_deformation.cpp
examples/thermomechanics/thermal_deformation_heat_transfer.cpp
src/CabanaPD_ForceModels.hpp
src/CabanaPD_HeatTransfer.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
src/force/CabanaPD_ContactModels.hpp
src/force/CabanaPD_ForceModels_LPS.hpp
src/force/CabanaPD_ForceModels_PMB.hpp
src/force/CabanaPD_Force_LPS.hpp
src/force/CabanaPD_Force_PMB.hpp
src/force/CabanaPD_HertzianContact.hpp
unit_test/tstForce.hpp
unit_test/tstHertz.hpp

Extracted from plasticity #142 
Fracture is now the default; similarly elastic is the default in preparation for plasticity models.

Rename model tags

---

src/CabanaPD_ForceModels.hpp
src/CabanaPD_Solver.hpp
src/force/CabanaPD_ContactModels.hpp
src/force/CabanaPD_ForceModels_LPS.hpp
src/force/CabanaPD_ForceModels_PMB.hpp
src/force/CabanaPD_Force_Contact.hpp
src/force/CabanaPD_Force_HertzianContact.hpp
src/force/CabanaPD_Force_LPS.hpp
src/force/CabanaPD_Force_PMB.hpp
src/force/CabanaPD_HertzianContact.hpp
unit_test/tstForce.hpp

First step in moving towards single force classes per pair/state/contact forms
- Remove unused "set" functions and default constructors
- Move repeated force class details into the base pmb/lps models

Move force details into models

---

examples/mechanics/crack_branching.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/kalthoff_winkler.cpp
examples/thermomechanics/thermal_crack.cpp
examples/thermomechanics/thermal_deformation.cpp
examples/thermomechanics/thermal_deformation_heat_transfer.cpp
src/CabanaPD_Force.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
src/force/CabanaPD_Force_LPS.hpp
src/force/CabanaPD_Force_PMB.hpp
unit_test/tstForce.hpp
unit_test/tstHertz.hpp

Fracture details (bond table) now belongs to the force class itself (as with the neighbor list)
This enables matching arguments for each force/energy update and a single solver class 
Something to consider - this exposes a prenotch option that is not functional for a non-fracture system (guarded by a static assert)

Unify solvers

---

examples/mechanics/crack_branching.cpp
examples/mechanics/elastic_wave.cpp
examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/kalthoff_winkler.cpp
examples/mechanics/random_cracks.cpp
examples/thermomechanics/thermal_crack.cpp
examples/thermomechanics/thermal_deformation.cpp
examples/thermomechanics/thermal_deformation_heat_transfer.cpp
examples/thermomechanics/thermal_deformation_heat_transfer_prenotched.cpp

Changed " Use default Kokkos spaces" to "Choose Kokkos spaces" in all examples
Removed " FIXME: set halo width based on delta" in all examples

Fixed comments in examples

---

examples/dem/powder_fill.cpp
examples/thermomechanics/thermal_crack.cpp
examples/thermomechanics/thermal_deformation.cpp
src/CabanaPD_BodyTerm.hpp
src/CabanaPD_Boundary.hpp
src/CabanaPD_Output.hpp
src/CabanaPD_Particles.hpp

If BC or body terms are created prior to ghost particles (or are otherwise out of date by the time it is applied in the solver) many issues ensue due to out of date slices
Change required for body term interface

Check boundary condition particle count

---

examples/mechanics/fragmenting_cylinder.cpp
examples/mechanics/inputs/fragmenting_cylinder.json

(1) Replaced hardcoded cylinder height with a json input.
(2) Fixed definition of zfactor to depend on cylinder dimensions instead of box dimensions.
(3) Added z_center for consistency.

Fixed fragmenting cylinder example

---

src/CabanaPD_HeatTransfer.hpp

fixup: remove unused thermal stretch in heat transfer

---

examples/mechanics/crack_branching.cpp
examples/mechanics/dogbone_tensile_test.cpp
examples/mechanics/random_cracks.cpp
examples/thermomechanics/thermal_deformation_heat_transfer.cpp
examples/thermomechanics/thermal_deformation_heat_transfer_prenotched.cpp
src/CabanaPD_Boundary.hpp

Remove the need for user-level vectors; enables different region types for a single BC
For now, remove the user-level allocation guess (not being used). Could be added back with extra constructors instead

Variadic boundary conditions

---

README.md
examples/mechanics/CMakeLists.txt
examples/mechanics/crack_branching.cpp
examples/mechanics/inputs/plate_with_hole.json
examples/mechanics/plate_with_hole.cpp
src/CabanaPD_Force.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
src/force/CabanaPD_Contact.hpp
src/force/CabanaPD_Hertzian.hpp
src/force/CabanaPD_LPS.hpp
src/force/CabanaPD_PMB.hpp
unit_test/tstForce.hpp

Added virial stress to particles.hpp and the HDF5 output for the pmb model. 
Added logic for calculating virial stress in compute full energy in force_pmb.hpp. 
Compiles and runs kalthoff winkler, however the virial stress in the output is zero. 
I think the forces may not be being calculated properly in the energy logic. I'm also unsure of how to handle bond breakage here, but my entire approach may be wrong so this might be totally unnecessary

Virial stress

---

src/force/CabanaPD_PMB.hpp

Not used for elastic (pass j as a placeholder); must be neighbor index for plastic stretch (n)
Mistake in #142

Pass neighbor index for plastic stretch array

---

src/CabanaPD_ForceModels.hpp
src/CabanaPD_HeatTransfer.hpp
src/force/CabanaPD_LPS.hpp
src/force/CabanaPD_PMB.hpp
src/force_models/CabanaPD_LPS.hpp
src/force_models/CabanaPD_PMB.hpp

Refactor extracted from multi-material; the functor interface will enable passing through the multi-material models.
Also:
1. Redefine model inheritance to avoid diamonds (separate base thermal, fracture, plasticity, etc.)
2. Remove unused child model typedefs

Rewrite model with tagged functor interfaces

---

src/CabanaPD_OutputProfiles.hpp

The function OutputTimeSeries was only outputting single precision when using it for the dogbone tensile test example.

Increase region output precision

---

src/CabanaPD_Force.hpp
src/CabanaPD_HeatTransfer.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Types.hpp
src/force/CabanaPD_Contact.hpp
src/force/CabanaPD_Hertzian.hpp
src/force/CabanaPD_LPS.hpp
src/force/CabanaPD_PMB.hpp
src/force_models/CabanaPD_Contact.hpp
src/force_models/CabanaPD_Hertzian.hpp
src/force_models/CabanaPD_LPS.hpp
unit_test/tstForce.hpp

Currently only the exact model form is usable by the force class. Multi-material models and more general flexibility (e.g. combining with linearized models) require a separation of the specialization tags for force classes

Simplify force bridge pattern and model templates

---

src/force/CabanaPD_LPS.hpp
src/force/CabanaPD_PMB.hpp

Caused bounds error if using plasticity. Unused for elastic models

Fix energy neighbor index for plasticity

---

src/CabanaPD_Geometry.hpp

This finally fixes an issue for systems with larger regions (often boundary conditions) than was initially allocated (50% of the local particles as a guess)
The problem stemmed from capture of the index_space size from the initial pass, rather than both times the loop is called

Fix region/BC initial guess

---

src/CabanaPD_Solver.hpp

- Neighbor time after the initial build was not included in the final output. This simplifies and unifies the timing output for per-step and final neighbor details. It is also no longer included in init so that there are not overlaps in timing output. Most of the line changes come from reordering output
- Also removes a definition of total time based on subsets of timing, instead

Simplify neighbor timers

---

.github/workflows/Nightly.yml

Incompatibility with Kokkos `develop` breaks Cabana without this flag

Use Kokkos legacy Views for nightly builds

---

examples/mechanics/inputs/fragmenting_cylinder.json
src/CabanaPD_Output.hpp
src/CabanaPD_Particles.hpp
src/CabanaPD_Solver.hpp
src/CabanaPD_Timer.hpp
src/CabanaPD_Types.hpp

Timings differ for:
- PD only (only output final neighbor time)
- DEM only (output neighbor time per step)
- Hybrid (output both PD and DEM force time and neighbor time)
Simplify internal solver timers as well

Differentiate timing per run type

---

src/CabanaPD_Types.hpp
src/force_models/CabanaPD_LPS.hpp
src/force_models/CabanaPD_PMB.hpp
unit_test/CMakeLists.txt
unit_test/tstForce.hpp
unit_test/tstHertz.hpp
unit_test/tstHertzJKR.hpp
unit_test/tstNormalRepulsion.hpp

Construction of temperature dependent plasticity did not work. It is now
`CabanaPD::ForceModel force_model( model_type{}, ElasticPerfectlyPlastic{}, delta, K, G0, sigma_y, temp, alpha, temp0 );`
- New tests for all PMB/LPS/contact models were added.
- New heat transfer + plasticity model was added.

Test model construction and fix thermal plasticity model

---

src/CabanaPD_HeatTransfer.hpp
src/CabanaPD_Solver.hpp

Remove explicit model requirements for heat transfer following #218
This adds the same model generality for heat transfer as in the force update; the plastic model not defining a non-fracture variant, but previously expecting one for inheritance in heat transfer, exemplifies the issue.

FIx heat transfer with plasticity
